<?php
/**
 * Generated by the WordPress Meta Box Generator
 * https://jeremyhixon.com/tool/wordpress-meta-box-generator/
 * 
 * Retrieving the values:
 * create_at = get_post_meta( get_the_ID(), 'twchr-from-api_create_at', true )
 * description = get_post_meta( get_the_ID(), 'twchr-from-api_description', true )
 * duration = get_post_meta( get_the_ID(), 'twchr-from-api_duration', true )
 * id = get_post_meta( get_the_ID(), 'twchr-from-api_id', true )
 * languaje = get_post_meta( get_the_ID(), 'twchr-from-api_languaje', true )
 * muted_segment = get_post_meta( get_the_ID(), 'twchr-from-api_muted_segment', true )
 * published_at = get_post_meta( get_the_ID(), 'twchr-from-api_published_at', true )
 * stream_id = get_post_meta( get_the_ID(), 'twchr-from-api_stream_id', true )
 * thumbnail_url = get_post_meta( get_the_ID(), 'twchr-from-api_thumbnail_url', true )
 * type = get_post_meta( get_the_ID(), 'twchr-from-api_type', true )
 * url = get_post_meta( get_the_ID(), 'twchr-from-api_url', true )
 * user_id = get_post_meta( get_the_ID(), 'twchr-from-api_user_id', true )
 * user_login = get_post_meta( get_the_ID(), 'twchr-from-api_user_login', true )
 * user_name = get_post_meta( get_the_ID(), 'twchr-from-api_user_name', true )
 * view_count = get_post_meta( get_the_ID(), 'twchr-from-api_view_count', true )
 * viewble = get_post_meta( get_the_ID(), 'twchr-from-api_viewble', true )
 * title = get_post_meta( get_the_ID(), 'twchr-from-api_title', true )
 */


 
function twitcher_stream_meta_box_content($post){
	$values    = get_post_custom( $post->ID );
	//show_dump($values);
	?>
	<style>
            a.twchr_button_get_videos {
                text-decoration: none;
                padding: 5px 10px;
                display: block;
                margin-bottom: 10pt;
                width: max-content;
                border-radius: 5px;
                background-color: var(--twchr-purple);
                color: #fff;
            }

            stream.twchr_modal_get_videos{
                display: none;
            }

            stream.twchr_modal_get_videos.active {
                max-width:100%;
                position: static;
    			margin-bottom: 1cm;
                box-shadow: 0 0 3px rgba(0, 0, 0, .5);
                display: block;
            }

            .twchr-modal .twchr_help_button {
                display: block;
                width: 40px;
                height: 40px;
                background-image: url(<?= plugins_url('twitcher/includes/assets/help.png')?>);
                background-size: contain;
                background-repeat: no-repeat;
                margin-right: 6pt;
            }

			#twitcher_stream metabox{
				display: grid;
				grid-template-columns:1fr 1fr 1fr;
				row-gap:15px;
			}

			#twitcher_stream metabox label{
				display: grid;
				grid-template-columns:30% 60%;
			}

			#twitcher_stream metabox input{
				border:1px solid var(--twchr-purple);
				box-shadow:5px 6px 5px #00000012 inset;
			}

        </style>
        <a id="twchr-gutemberg-modal-button" class="twchr_button_get_videos"
            href="#"><?php _e('Asign Twitch Streaming','twitcher')?>
		</a>
		<stream class="twchr_modal_get_videos twchr-modal">
            <div class="twchr-modal-selection_close">
                x
            </div>
            <div class="twchr-modal-selection__info">
                <h3><?php _e('Asign video to post','twitcher') ?></h3>

                <picture>
                    <img src="<?= plugins_url('/twitcher/includes/assets/Isologo_twitcher.svg')?>" alt="logo-twitcher">
                </picture>
            </div>

            <div id="twchr_button_get_videos__content">
                <ul class="twchr-modal-selection__list">
                    <li><?= __('Streaming name','twitcher'); ?></li>
                    <li><?= __('Date','twitcher'); ?></li>
                    <li><?= __('Already saved?','twitcher'); ?></li>
                    <li><?= __('Import','twitcher'); ?></li>
                </ul>
                <div class="content">

                </div>
            </div>

            <div class="twchr-modal-footer">
                <span class="twchr_help_button">
                    <p><?php _e('The folowing list is the avaiable videos in your twitch account. Select the video that you want to asign to this post.','twitcher'); ?>
                    </p>
                    
                </span>
                <button id="twchr-modal-selection__btn"><?= __('Asign','twitcher');?></button>
            </div>
        </stream>
    <metabox>
		<label>create_at<input name='twchr-from-api_create_at' type="text"></label>
		<label>description<input name='twchr-from-api_description' type="text"></label>
		<label>duration<input name='twchr-from-api_duration' type="text"></label>
		<label>id<input name='twchr-from-api_id' type="text"></label>
		<label>languaje<input name='twchr-from-api_languaje' type="text"></label>
		<label>muted_segment<input name='twchr-from-api_muted_segment' type="text"></label>
		<label>published_at<input name='twchr-from-api_published_at' type="text"></label>
		<label>stream_id<input name='twchr-from-api_stream_id' type="text"></label>
		<label>thumbnail_url<input name='twchr-from-api_thumbnail_url' type="text"></label>
		<label>type<input name='twchr-from-api_type' type="text"></label>
		<label>url<input name='twchr-from-api_url' type="text"></label>
		<label>user_id<input name='twchr-from-api_user_id' type="text"></label>
		<label>user_login<input name='twchr-from-api_user_login' type="text"></label>
		<label>user_name<input name='twchr-from-api_user_name' type="text"></label>
		<label>view_count<input name='twchr-from-api_view_count' type="text"></label>
		<label>viewble<input name='twchr-from-api_viewble' type="text"></label>
		<label>title<input name='twchr-from-api_title' type="text"></label>
	</metabox>
	
        <script>
		const twchr_gutember_modal_button = document.querySelector("#twchr-gutemberg-modal-button");
		twchr_gutember_modal_button.addEventListener('click',()=>{
			twchr_modal.classList.toggle("active");
            const user_id = tchr_vars_admin.twitcher_data_broadcaster.id;
            const client_id = tchr_vars_admin.twchr_keys['client-id'];
            const appToken = tchr_vars_admin.twchr_app_token;
            tchr_get_clips(appToken,client_id,user_id)
		});
        const twchr_modal = document.querySelector(".twchr_modal_get_videos.twchr-modal");
        const twchr_modal_button_close = document.querySelector(".twchr_modal_get_videos.twchr-modal .twchr-modal-selection_close");

        twchr_modal_button_close.addEventListener('click', e => {
            twchr_modal.classList.remove('active');
        });

        

        
        </script>
	<?php
}

function twitcher_stream_metabox(){
	//add_meta_box($id:string,$title:string,$callback:callable,$screen:string|array|WP_Screen|null,$context:string,$priority:string,$callback_args:array|null )
	add_meta_box( 'twitcher_stream', 'Twitcher data', 'twitcher_stream_meta_box_content', 'twchr_streams', 'normal', 'high' );
}

add_action('add_meta_boxes','twitcher_stream_metabox');


function twitcher_stream_metabox_save($post_id){
/* 
Antes de guardar la información, necesito verificar tres cosas:
	1. Si la entrada se está autoguardando
	2. Comprobar que el usuario actual puede realmente modificar este contenido.
*/
	
	if (! current_user_can( 'edit_posts' )) {
        return;
    }		
	

		$allowed = array();
		if ( isset( $_POST['twitcher_stream_dateTime'] ) ) {
			update_post_meta( $post_id, 'twitcher_stream_dateTime', wp_kses( $_POST['twitcher_stream_dateTime'], $allowed ) );
		}

		if( isset( $_POST['twchr_streams__yt-link-video-src'] )){
			update_post_meta( $post_id, 'twchr_streams__yt-link-video-src', wp_kses( $_POST['twchr_streams__yt-link-video-src'], $allowed ) );
		}

		if( isset( $_POST['twchr_stream_src_priority'] )){
			update_post_meta( $post_id, 'twchr_stream_src_priority', wp_kses( $_POST['twchr_stream_src_priority'], $allowed ) );
		}
	  
}


add_action( 'save_post', 'twitcher_stream_metabox_save' );