<?php
/**
 * Generated by the WordPress Meta Box Generator
 * https://jeremyhixon.com/tool/wordpress-meta-box-generator/
 * 
 * Retrieving the values:
 * start date = get_post_meta( get_the_ID(), 'twchr_stream_data_start-date', true )
 * start time = get_post_meta( get_the_ID(), 'twchr_stream_data_start-time', true )
 * is_serie = get_post_meta( get_the_ID(), 'twchr_stream_data_is_serie', true )
 * duration = get_post_meta( get_the_ID(), 'twchr_stream_data_duration', true )
 * category = get_post_meta( get_the_ID(), 'twchr_stream_data_category', true )
 */



 
function twchr_stream_data_meta_box_content($post){
	$values    = get_post_custom( $post->ID );
	//show_dump($values);
	$dateTime = isset($values['twchr_stream_data_dateTime'][0]) ? $values['twchr_stream_data_dateTime'][0] : '';
	$dateTimeTwitch = isset($values['twchr-from-api_create_at'][0]) ? $values['twchr-from-api_create_at'][0] : false;
	$yt_url = get_post_meta( get_the_ID(), 'twchr_streams__yt-link-video-src', true );
	$select = isset($values['twchr_stream_src_priority']) ? $values['twchr_stream_src_priority'][0] : ''; 
	
	?>
    <metabox>
        <div>
			<picture>
				<img src="<?php echo TWCHR_URL_ASSETS.'logo_menu.svg' ?>" alt="logo-twitch">
			</picture>
			<label >Fecha y hora del streming <input <?php echo  $dateTimeTwitch == false ? null : 'disabled'?> type="<?php echo  $dateTimeTwitch == false ? "datetime-local" : "text"?>" name='twchr_stream_data_dateTime' value="<?php if($dateTimeTwitch){echo $dateTimeTwitch; }else{echo $dateTime;}  ?>"></label>
		</div>
		<div>
			<lablel><?php twchr_esc_i18n('Source Priority','html'); ?></lablel>
			<select name="twchr_stream_src_priority">
				<option value="tw" <?php selected($select,'tw')?>>Twitch</option>
				<option value="yt" <?php selected($select,'yt')?>>Youtube</option>
			</select>
			<label>Youtbe URL <input type="text" name='twchr_streams__yt-link-video-src' value="<?php echo  $yt_url != false ? $yt_url : ''?>"></label>
		</div>
	</metabox>
	<?php
}

function twchr_stream_data_metabox(){
	//add_meta_box($id:string,$title:string,$callback:callable,$screen:string|array|WP_Screen|null,$context:string,$priority:string,$callback_args:array|null )
	add_meta_box( 'twchr_stream_data', 'Twitcher data', 'twchr_stream_data_meta_box_content', 'twchr_streams', 'normal', 'high' );
}

add_action('add_meta_boxes','twchr_stream_data_metabox');


function twchr_stream_data_metabox_save($post_id){
/* 
Antes de guardar la información, necesito verificar tres cosas:
	1. Si la entrada se está autoguardando
	2. Comprobar que el usuario actual puede realmente modificar este contenido.
*/
	
	if (! current_user_can( 'edit_posts' )) {
        return;
    }		
	

		$allowed = array();
		if ( isset( $_POST['twchr_stream_data_dateTime'] ) ) {
			update_post_meta( $post_id, 'twchr_stream_data_dateTime', wp_kses( $_POST['twchr_stream_data_dateTime'], $allowed ) );
		}

		if( isset( $_POST['twchr_streams__yt-link-video-src'] )){
			update_post_meta( $post_id, 'twchr_streams__yt-link-video-src', wp_kses( $_POST['twchr_streams__yt-link-video-src'], $allowed ) );
		}

		if( isset( $_POST['twchr_stream_src_priority'] )){
			update_post_meta( $post_id, 'twchr_stream_src_priority', wp_kses( $_POST['twchr_stream_src_priority'], $allowed ) );
		}
	  
}


add_action( 'save_post', 'twchr_stream_data_metabox_save' );
