name: PHP CodeSniffer twitcher

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4
    - name: Install PHP_CodeSniffer
      run: |
        wget https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
        chmod +x phpcs.phar
        mv phpcs.phar /usr/local/bin/phpcs
    - name: Run PHP_CodeSniffer
      run: |
        phpcs --report=WordPress-Core --standard=phpcs-report.xml